fixes #50 - Adds new code highlighting for prism
webcompat/design pull request #54
Opened 2017-11-16 13:32 UTC by madeleine-neumann-9elements

2017-11-16 14:58 UTC, zoepage requested changes

2017-11-16 14:58 UTC, zoepage commented on docs/index.html
> +		<link rel="stylesheet" href="css/lib/prism-gh-theme.css" />		<link rel="stylesheet" href="css/styleguide.css" />
bitte über main.css einbinden.

2017-11-16 14:58 UTC, zoepage commented on docs/index.html
> +
das code beispiel kann eingentlich raus. das adden wir dann in die comment section und machen n neues issue auf falls was ist.

2017-11-17 10:09 UTC, kotzendekrabbe approved these changes

2017-11-17 10:11 UTC, merged