Fixes #30 -  adds explanation for Labels
webcompat/design pull request #68
Opened 2017-11-17 17:06 UTC by madeleine-neumann

2017-11-17 17:14 UTC, zoepage requested changes

2017-11-17 17:14 UTC, zoepage commented on docs/index.html
> +					This Module helps you to set filter labels. The ID <code>filter-issue-status</code> wraps the labels. The <code>filter-label</code> class makes sure, that all labels are wrapped in a container w
This module helps to add a label to the issue, which indicates the status of an issue. 
There are 6 different states.

- Needs Triage 
- Needs Diagnosis
- Needs Contact
- Ready for Outreach
- Site Contacted
- Closed

2017-11-17 17:14 UTC, zoepage commented on docs/index.html
> +				<p>There are 6 labels you can use:</p>
this and the next paragraph can be removed as we have the context above. 
(first context, then code explanation).

2017-11-17 19:59 UTC, madeleine-neumann commented
@zoepage another review?

2017-11-17 20:38 UTC, zoepage commented
@madeleine-neumann merge conflicts?

2017-11-17 21:17 UTC, madeleine-neumann commented
@zoepage done

2017-11-18 13:42 UTC, zoepage approved these changes

2017-11-18 13:42 UTC, merged